### ISSUE TITLE
Usage clarification 

### ISSUE THREAD

**Issue by peikovakate** [heyuan7676/ts_eQTLs#1]
Hello, I am trying to use your algorithm for eQTL data from other datasets than GTEx. 
Can you please give some clarification:
- Why do you use standard deviation as weights and not a standard error?
- It is unclear how I should use `run_MF_train_coph.R` script for selecting parameters.
- Can you suggest how `alpha` and `lambda` parameters can be selected? 
- Should I use the same number of iterations for `run_MF.R` and `run_MF_train_coph.R`?

Also, could you describe the input for mapping eqtls to factors?

**Comment by heyuan7676** [comment]
Hi, thank you for your questions!

- For each eQTL, I used the reciprocal of standard error as the weight. Could you let me know if any documentation might be inaccurate? 

- run_MF_train_coph.R was to compute the cophenetic coefficient and the correlation between factors. You'll need to run run_MF_train_coph.sh multiple times with the set of parameters you'd like to test. The detailed process of choosing the parameters could be found in the preprint, section "Model selection" in Methods. (https://www.biorxiv.org/content/10.1101/785584v1.full.pdf)

- I'd recommend first running with parameters with large gaps, and have an idea of the range, and then narrow down to do grid search. 

- Yes, since the parameters were chosen based on this set of iterations. 

- Mapping of eQTL to factors could be found in the "Assignment of eQTLs to factors" section in Methods in the preprint mentioned above.

Please let me know if anything is unclear. Thank you!


Best,
Yuan

**Comment by peikovakate** [comment]
Thank you for your quick reply,

>  For each eQTL, I used the reciprocal of standard error as the weight. Could you let me know if any documentation might be inaccurate?

In the "Method" section, "Data" subsection you mentioned that collected effect size and standard deviation from cis-eQTL analysis. I guess this line confused me. 


Regarding the mapping eQTLs, 
in the `readin_YWX.R` file you read the `tissues.txt` file.
```
tissues = read.table('tissues.txt', sep='\t', header=F, stringsAsFactors = F)
tissues = as.vector(tissues['V1'])
comp = apply(X, 2, function(x) tissues[which(x>0.01), ])
```

Could you please explain what information does this file contain?

**Comment by heyuan7676** [comment]
Hi!

This should be a typo in the pre-print, it was corrected in the newly devised version under review :) 


Sure. The `tissues.txt` is a file with the first column being the tissues names. In GTEx scenario, it's a 49 x 1 matrix. 

comp is a list, with each element including the tissues represented in each factor in X. It provides the information in the panel titles for Supplementary figure 2 in the preprint.  

Please let me know if anything is unclear. Thank you!
